/**
 * Recommended books: Western Christian culture + bioconservatism.
 * Buy links use Amazon Associates (referral commission).
 */

import { amazonProductUrl, amazonSearchUrl } from '@/lib/config/affiliates';

export type BookTheme = 'western_christian' | 'bioconservatism' | 'both';

export interface RecommendedBook {
  id: string;
  title: string;
  titleEs: string;
  author: string;
  blurbEn: string;
  blurbEs: string;
  themes: BookTheme[];
  /** Amazon ASIN when known (also used for cover images) */
  asin?: string;
  /** Optional explicit cover image URL */
  coverUrl?: string;
  /** Cover color accent for card */
  accent: string;
  /** Emoji / short mark when no cover image */
  mark: string;
}

export const RECOMMENDED_BOOKS: RecommendedBook[] = [
  {
    id: 'mere-christianity',
    title: 'Mere Christianity',
    titleEs: 'Mero cristianismo',
    author: 'C. S. Lewis',
    blurbEn: 'Classic defense of the Christian faith that shaped the West.',
    blurbEs: 'Defensa clásica de la fe cristiana que forjó Occidente.',
    themes: ['western_christian'],
    asin: '0060652926',
    coverUrl: '/freedom/book-covers/mere-christianity.jpg',
    accent: '#C4A574',
    mark: '✝',
  },
  {
    id: 'abolition-of-man',
    title: 'The Abolition of Man',
    titleEs: 'La abolición del hombre',
    author: 'C. S. Lewis',
    blurbEn: 'Against moral relativism and the remaking of human nature.',
    blurbEs: 'Contra el relativismo moral y la reingeniería de la naturaleza humana.',
    themes: ['both'],
    asin: '0060652942',
    coverUrl: '/freedom/book-covers/abolition-of-man.jpg',
    accent: '#8B7355',
    mark: '⚖',
  },
  {
    id: 'dominion',
    title: 'Dominion',
    titleEs: 'Dominio',
    author: 'Tom Holland',
    blurbEn: 'How Christianity remade the West — and still does.',
    blurbEs: 'Cómo el cristianismo rehizo Occidente — y aún lo hace.',
    themes: ['western_christian'],
    asin: '0465093507',
    coverUrl: '/freedom/book-covers/dominion.jpg',
    accent: '#9B6B4A',
    mark: '🏛',
  },
  {
    id: 'benedict-option',
    title: 'The Benedict Option',
    titleEs: 'La opción benedictina',
    author: 'Rod Dreher',
    blurbEn: 'Building resilient Christian communities in a post-Christian age.',
    blurbEs: 'Comunidades cristianas resilientes en una era postcristiana.',
    themes: ['western_christian'],
    asin: '0735213291',
    coverUrl: '/freedom/book-covers/benedict-option.jpg',
    accent: '#6B8F6E',
    mark: '🛡',
  },
  {
    id: 'live-not-by-lies',
    title: 'Live Not by Lies',
    titleEs: 'No vivir de mentiras',
    author: 'Rod Dreher',
    blurbEn: 'Soft totalitarianism and the Christian duty to tell the truth.',
    blurbEs: 'Totalitarismo blando y el deber cristiano de decir la verdad.',
    themes: ['western_christian'],
    asin: '0593087395',
    coverUrl: '/freedom/book-covers/live-not-by-lies.jpg',
    accent: '#7A6B5A',
    mark: '🕯',
  },
  {
    id: 'rise-triumph-modern-self',
    title: 'The Rise and Triumph of the Modern Self',
    titleEs: 'El auge y triunfo del yo moderno',
    author: 'Carl R. Trueman',
    blurbEn: 'How expressive individualism dismantled Christian anthropology.',
    blurbEs: 'Cómo el individualismo expresivo desmanteló la antropología cristiana.',
    themes: ['both'],
    asin: '1433556332',
    coverUrl: '/freedom/book-covers/rise-triumph-modern-self.jpg',
    accent: '#5C6B8A',
    mark: '🧠',
  },
  {
    id: 'strange-new-world',
    title: 'Strange New World',
    titleEs: 'Un mundo extraño y nuevo',
    author: 'Carl R. Trueman',
    blurbEn: 'Accessible guide to identity culture and Christian response.',
    blurbEs: 'Guía accesible a la cultura de la identidad y la respuesta cristiana.',
    themes: ['both'],
    asin: '1433579308',
    coverUrl: '/freedom/book-covers/strange-new-world.jpg',
    accent: '#4A7A8A',
    mark: '🌍',
  },
  {
    id: 'what-means-human',
    title: 'What It Means to Be Human',
    titleEs: 'Qué significa ser humano',
    author: 'O. Carter Snead',
    blurbEn: 'Bioconservative law: embodiment, vulnerability, human dignity.',
    blurbEs: 'Derecho bioconservador: cuerpo, vulnerabilidad y dignidad humana.',
    themes: ['bioconservatism'],
    asin: '0674987721',
    coverUrl: '/freedom/book-covers/what-means-human.jpg',
    accent: '#4A9EFF',
    mark: '🧬',
  },
  {
    id: 'life-liberty-dignity',
    title: 'Life, Liberty and the Defense of Dignity',
    titleEs: 'Vida, libertad y defensa de la dignidad',
    author: 'Leon R. Kass',
    blurbEn: 'Foundational bioconservatism against biotech hubris.',
    blurbEs: 'Bioconservadurismo fundacional frente a la soberbia biotecnológica.',
    themes: ['bioconservatism'],
    asin: '159403039X',
    coverUrl: '/freedom/book-covers/life-liberty-dignity.jpg',
    accent: '#3D7AB5',
    mark: '🫀',
  },
  {
    id: 'why-liberalism-failed',
    title: 'Why Liberalism Failed',
    titleEs: 'Por qué falló el liberalismo',
    author: 'Patrick J. Deneen',
    blurbEn: 'Critique of liberal order and recovery of rooted tradition.',
    blurbEs: 'Crítica del orden liberal y recuperación de la tradición arraigada.',
    themes: ['western_christian'],
    asin: '0300223447',
    coverUrl: '/freedom/book-covers/why-liberalism-failed.jpg',
    accent: '#8B5A4A',
    mark: '📜',
  },
  {
    id: 'how-should-we-then-live',
    title: 'How Should We Then Live?',
    titleEs: '¿Cómo viviremos entonces?',
    author: 'Francis A. Schaeffer',
    blurbEn: 'Rise and decline of Western thought and Christian culture.',
    blurbEs: 'Auge y declive del pensamiento occidental y la cultura cristiana.',
    themes: ['western_christian'],
    asin: '0891072925',
    coverUrl: '/freedom/book-covers/how-should-we-then-live.jpg',
    accent: '#A67C52',
    mark: '📖',
  },
  {
    id: 'case-against-sexual-revolution',
    title: 'The Case Against the Sexual Revolution',
    titleEs: 'El caso contra la revolución sexual',
    author: 'Louise Perry',
    blurbEn: 'Post-liberal case for restraint, family, and the body.',
    blurbEs: 'Argumento postliberal por la contención, la familia y el cuerpo.',
    themes: ['bioconservatism'],
    asin: '1509549997',
    coverUrl: '/freedom/book-covers/case-against-sexual-revolution.jpg',
    accent: '#B07A8A',
    mark: '🏠',
  },
  {
    id: 'kaiser-tirania-igualdad',
    title: 'The Tyranny of Equality',
    titleEs: 'La tiranía de la igualdad',
    author: 'Axel Kaiser',
    blurbEn: 'Why egalitarian projects erode freedom and prosperity.',
    blurbEs: 'Por qué el proyecto igualitario destruye libertades y prosperidad.',
    themes: ['both'],
    asin: '8423426580',
    coverUrl: '/freedom/book-covers/kaiser-tirania-igualdad.jpg',
    accent: '#C9A227',
    mark: '🇨🇱',
  },
  {
    id: 'kaiser-economista-callejero',
    title: 'The Street Economist',
    titleEs: 'El economista callejero',
    author: 'Axel Kaiser',
    blurbEn: '15 lessons of economics against demagogues and politicians.',
    blurbEs: '15 lecciones de economía para sobrevivir a políticos y demagogos.',
    themes: ['western_christian'],
    asin: '6075693270',
    coverUrl: '/freedom/book-covers/kaiser-economista-callejero.jpg',
    accent: '#D4AF37',
    mark: '💰',
  },
  {
    id: 'kaiser-neoinquisicion',
    title: 'The Neo-Inquisition',
    titleEs: 'La neoinquisición',
    author: 'Axel Kaiser',
    blurbEn: 'How progressive intolerance silences free thought.',
    blurbEs: 'Cómo la intolerancia progresista silencia el pensamiento libre.',
    themes: ['western_christian'],
    asin: '8423431576',
    coverUrl: '/freedom/book-covers/kaiser-neoinquisicion.jpg',
    accent: '#B8860B',
    mark: '🔥',
  },
  {
    id: 'kaiser-dogma-igualitario',
    title: 'Mental Parasites',
    titleEs: 'Parásitos mentales',
    author: 'Axel Kaiser',
    blurbEn: 'Seven progressive ideas that infect thought and society.',
    blurbEs: 'Siete ideas progresistas que infectan nuestro pensamiento y sociedad.',
    themes: ['both'],
    asin: '6075699953',
    coverUrl: '/freedom/book-covers/kaiser-dogma-igualitario.jpg',
    accent: '#DAA520',
    mark: '📉',
  },
  {
    id: 'kaiser-error-blanco',
    title: 'Nazi-Communism',
    titleEs: 'Nazi-Comunismo',
    author: 'Axel Kaiser',
    blurbEn: 'Why Marxist-Leninists and Nazi fascists are ideological twins.',
    blurbEs:
      'Porqué marxistas, leninistas y nazi-fascistas son gemelos ideológicos.',
    themes: ['bioconservatism'],
    asin: '6076391758',
    coverUrl: '/freedom/book-covers/kaiser-error-blanco.jpg',
    accent: '#CD853F',
    mark: '🧩',
  },
  {
    id: 'lukacs-neo-entes',
    title: 'Neo-Entities',
    titleEs: 'Neo entes',
    author: 'Miklós Lukács',
    blurbEn: 'Technology and anthropological change in the 21st century.',
    blurbEs: 'Tecnología y cambio antropológico en el siglo XXI.',
    themes: ['bioconservatism'],
    asin: '8419349658',
    coverUrl: '/freedom/book-covers/lukacs-neo-entes.jpg',
    accent: '#6A5ACD',
    mark: '🤖',
  },
  {
    id: 'lukacs-neo-religiones',
    title: 'Neo-Religions',
    titleEs: 'Neo-religiones',
    author: 'Miklós Lukács',
    blurbEn: 'Transhumanism and digital ideologies as new faiths.',
    blurbEs: 'Transhumanismo e ideologías digitales como nuevas religiones.',
    themes: ['both'],
    asin: '6124466049',
    coverUrl: '/freedom/book-covers/lukacs-neo-religiones.jpg',
    accent: '#7B68EE',
    mark: '⚡',
  },
  {
    id: 'lukacs-transhumanismo',
    title: 'Transhumanism and the Human Person',
    titleEs: 'Transhumanismo y persona humana',
    author: 'Miklós Lukács',
    blurbEn: 'Why the person cannot be reduced to code or hardware.',
    blurbEs: 'Por qué la persona no se reduce a código ni a hardware.',
    themes: ['bioconservatism'],
    asin: '6125038045',
    coverUrl: '/freedom/book-covers/lukacs-transhumanismo.jpg',
    accent: '#9370DB',
    mark: '🧬',
  },
  {
    id: 'munoz-atrapado-cuerpo',
    title: 'Trapped in the Wrong Body',
    titleEs: 'Atrapado en el cuerpo equivocado',
    author: 'Pablo Muñoz Iturrieta',
    blurbEn: 'Gender ideology vs science and philosophy.',
    blurbEs: 'La ideología de género frente a la ciencia y la filosofía.',
    themes: ['bioconservatism'],
    // Product sometimes delisted — buy link falls back to Amazon search
    coverUrl: '/freedom/book-covers/munoz-atrapado-cuerpo.jpg',
    accent: '#2E8B57',
    mark: '🔬',
  },
  {
    id: 'munoz-libertad-religiosa',
    title: 'Religious Freedom in the Public Square',
    titleEs: 'El significado de la libertad religiosa en la esfera pública',
    author: 'Pablo Muñoz Iturrieta',
    blurbEn: 'Faith and public reason in liberal democracies.',
    blurbEs: 'Fe y razón pública en las democracias liberales.',
    themes: ['western_christian'],
    coverUrl: '/freedom/book-covers/munoz-libertad-religiosa.jpg',
    accent: '#3CB371',
    mark: '⚖',
  },
  {
    id: 'munoz-ideologia-genero',
    title: 'Gender Ideology',
    titleEs: 'Ideología de género',
    author: 'Pablo Muñoz Iturrieta',
    blurbEn: 'Clear analysis of gender theory and its cultural costs.',
    blurbEs: 'Análisis claro de la teoría de género y su costo cultural.',
    themes: ['bioconservatism'],
    asin: '1532639725',
    coverUrl: '/freedom/book-covers/munoz-ideologia-genero.jpg',
    accent: '#228B22',
    mark: '🧭',
  },
  {
    id: 'laje-libro-negro',
    title: 'The Black Book of the New Left',
    titleEs: 'El libro negro de la nueva izquierda',
    author: 'Agustín Laje',
    blurbEn: 'With Nicolás Márquez — cultural Marxism mapped.',
    blurbEs: 'Con Nicolás Márquez — el mapa del marxismo cultural.',
    themes: ['western_christian'],
    asin: '987170746X',
    coverUrl: '/freedom/book-covers/laje-libro-negro.jpg',
    accent: '#8B0000',
    mark: '📕',
  },
  {
    id: 'laje-generacion-idiota',
    title: 'Idiot Generation',
    titleEs: 'Generación idiota',
    author: 'Agustín Laje',
    blurbEn: 'How youth were captured by progressive ideology.',
    blurbEs: 'Cómo la juventud fue capturada por la ideología progresista.',
    themes: ['both'],
    asin: '1400238560',
    coverUrl: '/freedom/book-covers/laje-generacion-idiota.jpg',
    accent: '#B22222',
    mark: '📱',
  },
  {
    id: 'laje-batalla-cultural',
    title: 'The Cultural Battle',
    titleEs: 'La batalla cultural',
    author: 'Agustín Laje',
    blurbEn: 'Strategy for conserving civilization in the culture war.',
    blurbEs: 'Estrategia para conservar la civilización en la batalla cultural.',
    themes: ['western_christian'],
    asin: '1400235995',
    coverUrl: '/freedom/book-covers/laje-batalla-cultural.jpg',
    accent: '#A52A2A',
    mark: '⚔',
  },
  {
    id: 'laje-globalismo',
    title: 'Globalism',
    titleEs: 'Globalismo',
    author: 'Agustín Laje',
    blurbEn: 'Globalist power and the defense of the nation.',
    blurbEs: 'El poder globalista y la defensa de la nación.',
    themes: ['western_christian'],
    asin: '1400331862',
    coverUrl: '/freedom/book-covers/laje-globalismo.jpg',
    accent: '#800000',
    mark: '🌐',
  },
  {
    id: 'kirk-right-wing-revolution',
    title: 'Right Wing Revolution',
    titleEs: 'Revolución de derecha',
    author: 'Charlie Kirk',
    blurbEn: 'How to beat the woke and save the West.',
    blurbEs: 'Cómo derrotar al woke y salvar Occidente.',
    themes: ['western_christian'],
    asin: '1735503797',
    coverUrl: '/freedom/book-covers/kirk-right-wing-revolution.jpg',
    accent: '#DC143C',
    mark: '🇺🇸',
  },
  {
    id: 'kirk-campus-battlefield',
    title: 'Campus Battlefield',
    titleEs: 'Campo de batalla en el campus',
    author: 'Charlie Kirk',
    blurbEn: 'How conservatives can win the battle on campus.',
    blurbEs: 'Cómo los conservadores pueden ganar en el campus.',
    themes: ['western_christian'],
    asin: '1642930946',
    coverUrl: '/freedom/book-covers/kirk-campus-battlefield.jpg',
    accent: '#B22222',
    mark: '🎓',
  },
  {
    id: 'kirk-maga-doctrine',
    title: 'The MAGA Doctrine',
    titleEs: 'La doctrina MAGA',
    author: 'Charlie Kirk',
    blurbEn: 'The essential ideas behind the America First movement.',
    blurbEs: 'Las ideas esenciales del movimiento America First.',
    themes: ['western_christian'],
    asin: '0062992133',
    coverUrl: '/freedom/book-covers/kirk-maga-doctrine.jpg',
    accent: '#CD5C5C',
    mark: '🦅',
  },
  {
    id: 'peterson-12-rules',
    title: '12 Rules for Life',
    titleEs: '12 reglas para vivir',
    author: 'Jordan B. Peterson',
    blurbEn: 'Antidote to chaos — responsibility, meaning, and order.',
    blurbEs: 'Antídoto al caos: responsabilidad, sentido y orden.',
    themes: ['both'],
    asin: '0345816021',
    coverUrl: '/freedom/book-covers/peterson-12-rules.jpg',
    accent: '#1E90FF',
    mark: '🦞',
  },
  {
    id: 'peterson-beyond-order',
    title: 'Beyond Order',
    titleEs: 'Más allá del orden',
    author: 'Jordan B. Peterson',
    blurbEn: '12 more rules — balance between structure and transformation.',
    blurbEs: '12 reglas más: equilibrio entre estructura y transformación.',
    themes: ['both'],
    asin: '0593084647',
    coverUrl: '/freedom/book-covers/peterson-beyond-order.jpg',
    accent: '#4169E1',
    mark: '🗺',
  },
  {
    id: 'peterson-maps-meaning',
    title: 'Maps of Meaning',
    titleEs: 'Mapas del sentido',
    author: 'Jordan B. Peterson',
    blurbEn: 'Myth, belief, and the architecture of belief systems.',
    blurbEs: 'Mito, creencia y la arquitectura de los sistemas de sentido.',
    themes: ['western_christian'],
    asin: '0415922224',
    coverUrl: '/freedom/book-covers/peterson-maps-meaning.jpg',
    accent: '#0000CD',
    mark: '🧭',
  },
  {
    id: 'peterson-we-who-wrestle',
    title: 'We Who Wrestle with God',
    titleEs: 'Los que luchan con Dios',
    author: 'Jordan B. Peterson',
    blurbEn: 'Biblical stories and the moral structure of reality.',
    blurbEs: 'Relatos bíblicos y la estructura moral de la realidad.',
    themes: ['western_christian'],
    asin: '0593542533',
    coverUrl: '/freedom/book-covers/peterson-we-who-wrestle.jpg',
    accent: '#191970',
    mark: '✝',
  },
  {
    id: 'murray-madness-crowds',
    title: 'The Madness of Crowds',
    titleEs: 'La locura de las masas',
    author: 'Douglas Murray',
    blurbEn: 'Gender, race, identity — and the new intolerance.',
    blurbEs: 'Género, raza, identidad — y la nueva intolerancia.',
    themes: ['both'],
    asin: '1635579988',
    coverUrl: '/freedom/book-covers/murray-madness-crowds.jpg',
    accent: '#708090',
    mark: '👥',
  },
  {
    id: 'murray-strange-death',
    title: 'The Strange Death of Europe',
    titleEs: 'La extraña muerte de Europa',
    author: 'Douglas Murray',
    blurbEn: 'Immigration, identity, and the loss of civilizational confidence.',
    blurbEs: 'Inmigración, identidad y la pérdida de confianza civilizatoria.',
    themes: ['western_christian'],
    asin: '1472958004',
    coverUrl: '/freedom/book-covers/murray-strange-death.jpg',
    accent: '#778899',
    mark: '🇪🇺',
  },
  {
    id: 'shapiro-right-side-history',
    title: 'The Right Side of History',
    titleEs: 'El lado correcto de la historia',
    author: 'Ben Shapiro',
    blurbEn: 'How reason and Judeo-Christian values built the West.',
    blurbEs: 'Cómo la razón y los valores judeocristianos construyeron Occidente.',
    themes: ['western_christian'],
    asin: '0062857908',
    coverUrl: '/freedom/book-covers/shapiro-right-side-history.jpg',
    accent: '#4682B4',
    mark: '✡',
  },
  {
    id: 'scruton-how-be-conservative',
    title: 'How to Be a Conservative',
    titleEs: 'Cómo ser conservador',
    author: 'Roger Scruton',
    blurbEn: 'Elegant defense of tradition, home, and the sacred.',
    blurbEs: 'Defensa elegante de la tradición, el hogar y lo sagrado.',
    themes: ['western_christian'],
    asin: '147296523X',
    coverUrl: '/freedom/book-covers/scruton-how-be-conservative.jpg',
    accent: '#556B2F',
    mark: '🍃',
  },
  {
    id: 'sowell-basic-economics',
    title: 'Basic Economics',
    titleEs: 'Economía básica',
    author: 'Thomas Sowell',
    blurbEn: 'Economics without jargon — incentives and trade-offs.',
    blurbEs: 'Economía sin jerga: incentivos y trade-offs.',
    themes: ['western_christian'],
    asin: '0465060730',
    coverUrl: '/freedom/book-covers/sowell-basic-economics.jpg',
    accent: '#2F4F4F',
    mark: '📊',
  },
  {
    id: 'hayek-road-serfdom',
    title: 'The Road to Serfdom',
    titleEs: 'Camino de servidumbre',
    author: 'F. A. Hayek',
    blurbEn: 'Why central planning leads to tyranny.',
    blurbEs: 'Por qué la planificación central conduce a la tiranía.',
    themes: ['western_christian'],
    asin: '0226320553',
    coverUrl: '/freedom/book-covers/hayek-road-serfdom.jpg',
    accent: '#696969',
    mark: '⛓',
  },
  {
    id: 'marquez-laje-guerra-cultural',
    title: 'The Black Book of the New Left',
    titleEs: 'El libro negro de la nueva izquierda',
    author: 'Nicolás Márquez & Agustín Laje',
    blurbEn: 'Practical map of cultural Marxism and the conflict in Latin America.',
    blurbEs: 'Mapa del marxismo cultural y el conflicto en América Latina.',
    themes: ['western_christian'],
    asin: '987170746X',
    coverUrl: '/freedom/book-covers/marquez-laje-guerra-cultural.jpg',
    accent: '#8B4513',
    mark: '📋',
  },
  {
    id: 'gloria-alvarez-como-hablar',
    title: 'How to Talk with a Progressive',
    titleEs: 'Cómo hablar con un progresista',
    author: 'Gloria Álvarez',
    blurbEn: 'Arguments for liberty against collectivist myths.',
    blurbEs: 'Argumentos por la libertad frente a mitos colectivistas.',
    themes: ['western_christian'],
    asin: '6075278460',
    coverUrl: '/freedom/book-covers/gloria-alvarez-como-hablar.jpg',
    accent: '#FF6347',
    mark: '🗣',
  },
  {
    id: 'vanessa-kaiser-feminismo',
    title: 'Progressivism and the Culture of Death',
    titleEs: 'El progresismo y la cultura de la muerte',
    author: 'Vanessa Kaiser',
    blurbEn:
      'Keys to understand the ideological project of the New Left and progressive culture.',
    blurbEs:
      'Claves para entender el proyecto ideológico y político de la Nueva Izquierda.',
    themes: ['both'],
    asin: '9566172192',
    coverUrl: '/freedom/book-covers/vanessa-kaiser-feminismo.jpg',
    accent: '#DB7093',
    mark: '♀',
  },
  {
    id: 'vanessa-kaiser-cultura',
    title: 'Progressivism Against the Will to Live',
    titleEs: 'El progresismo frente al deseo de vivir',
    author: 'Vanessa Kaiser',
    blurbEn: 'Liberty, life, and resistance to progressive ideology.',
    blurbEs: 'Libertad, vida y resistencia frente a la ideología progresista.',
    themes: ['western_christian'],
    asin: 'B0GXQZWVCH',
    coverUrl: '/freedom/book-covers/vanessa-kaiser-cultura.jpg',
    accent: '#C71585',
    mark: '✍',
  },
  {
    id: 'vance-hillbilly-elegy',
    title: 'Hillbilly Elegy',
    titleEs: 'Elegía hillbilly',
    author: 'J.D. Vance',
    blurbEn: 'Family, class, and the American dream in Appalachia.',
    blurbEs: 'Familia, clase y el sueño americano en los Apalaches.',
    themes: ['western_christian'],
    asin: '0062300547',
    coverUrl: '/freedom/book-covers/vance-hillbilly-elegy.jpg',
    accent: '#8B4513',
    mark: '🇺🇸',
  },
  {
    id: 'prince-civilian-warriors',
    title: 'Civilian Warriors',
    titleEs: 'Guerreros civiles',
    author: 'Erik D. Prince',
    blurbEn: 'The inside story of Blackwater and private security.',
    blurbEs: 'La historia interna de Blackwater y la seguridad privada.',
    themes: ['western_christian'],
    asin: '1591847451',
    coverUrl: '/freedom/book-covers/prince-civilian-warriors.jpg',
    accent: '#2F4F4F',
    mark: '🛡',
  },
  {
    id: 'wolf-bodies-of-evidence',
    title: 'The Bodies of Others',
    titleEs: 'Los cuerpos de los demás',
    author: 'Naomi Wolf',
    blurbEn: 'Pandemic power, tech, and the erosion of bodily freedom.',
    blurbEs: 'Poder pandémico, tecnología y la erosión de la libertad corporal.',
    themes: ['bioconservatism'],
    asin: '1737478566',
    coverUrl: '/freedom/book-covers/wolf-bodies-of-evidence.jpg',
    accent: '#9370DB',
    mark: '🔒',
  },
  {
    id: 'leake-mcCullough-courage',
    title: 'The Courage to Face COVID-19',
    titleEs: 'El valor de enfrentar el COVID-19',
    author: 'John Leake & Peter A. McCullough',
    blurbEn: 'Medical freedom, early treatment, and institutional failure.',
    blurbEs: 'Libertad médica, tratamiento temprano y fallo institucional.',
    themes: ['bioconservatism'],
    asin: '1510776791',
    coverUrl: '/freedom/book-covers/leake-mcCullough-courage.svg',
    accent: '#483D8B',
    mark: '💉',
  },
  {
    id: 'truesdell-homeschool',
    title: 'Anyone Can Homeschool',
    titleEs: 'Cualquiera puede educar en casa',
    author: 'Nicki Truesdell',
    blurbEn:
      'Overcoming obstacles to home education — practical guide for any family situation.',
    blurbEs:
      'Superar obstáculos a la educación en casa — guía práctica para cualquier familia.',
    themes: ['western_christian'],
    asin: 'B08GG2RKPN',
    coverUrl: '/freedom/book-covers/truesdell-homeschool.jpg',
    accent: '#CD853F',
    mark: '📚',
  },
  {
    id: 'prager-still-right',
    title: 'Still the Best Hope',
    titleEs: 'Sigue siendo la mejor esperanza',
    author: 'Dennis Prager',
    blurbEn: 'Why the American trinity (liberty, E Pluribus Unum, In God We Trust) matters.',
    blurbEs: 'Por qué la trinidad americana (libertad, E Pluribus Unum, In God We Trust) importa.',
    themes: ['western_christian'],
    asin: '1594036185',
    coverUrl: '/freedom/book-covers/prager-still-right.jpg',
    accent: '#1E3A5F',
    mark: '🗽',
  },
  {
    id: 'prager-rational-bible',
    title: 'The Rational Bible: Exodus',
    titleEs: 'La Biblia racional: Éxodo',
    author: 'Dennis Prager',
    blurbEn: 'Moral clarity from Torah for a confused age.',
    blurbEs: 'Claridad moral desde la Torá para una era confusa.',
    themes: ['western_christian'],
    asin: '1621577724',
    coverUrl: '/freedom/book-covers/prager-rational-bible.jpg',
    accent: '#2C4A6E',
    mark: '✡',
  },
  {
    id: 'robinson-enemy-state',
    title: 'Enemy of the State',
    titleEs: 'Enemigo del Estado',
    author: 'Tommy Robinson',
    blurbEn: 'Free speech, immigration, and the cost of dissent in the UK.',
    blurbEs: 'Libertad de expresión, inmigración y el costo de disentir en el Reino Unido.',
    themes: ['western_christian'],
    asin: '1913201083',
    coverUrl: '/freedom/book-covers/robinson-enemy-state.jpg',
    accent: '#000080',
    mark: '🇬🇧',
  },
  {
    id: 'iturralde-iglesia-comunismo',
    title: 'Church and Communism',
    titleEs: 'Iglesia y comunismo',
    author: 'Cristian Rodrigo Iturralde',
    blurbEn: 'Catholic resistance to communist ideology.',
    blurbEs: 'Resistencia católica a la ideología comunista.',
    themes: ['western_christian'],
    asin: '8411310450',
    coverUrl: '/freedom/book-covers/iturralde-iglesia-comunismo.jpg',
    accent: '#8B0000',
    mark: '✝',
  },
  {
    id: 'iturralde-leyendas-negras',
    title: 'Black Legends of the Church',
    titleEs: 'Leyendas negras de la Iglesia',
    author: 'Cristian Rodrigo Iturralde',
    blurbEn: 'Historical defense against anti-Catholic myths.',
    blurbEs: 'Defensa histórica frente a mitos anticatólicos.',
    themes: ['western_christian'],
    asin: '8411311015',
    coverUrl: '/freedom/book-covers/iturralde-leyendas-negras.jpg',
    accent: '#A0522D',
    mark: '📜',
  },
  {
    id: 'ismail-exponential-organizations',
    title: 'Exponential Organizations',
    titleEs: 'Organizaciones exponenciales',
    author: 'Salim Ismail',
    blurbEn: 'How tech-scale organizations outperform the rest.',
    blurbEs: 'Cómo las organizaciones a escala tecnológica superan al resto.',
    themes: ['western_christian'],
    asin: '1626814236',
    coverUrl: '/freedom/book-covers/ismail-exponential-organizations.jpg',
    accent: '#00CED1',
    mark: '🚀',
  },
  {
    id: 'maxwell-21-laws',
    title: 'The 21 Irrefutable Laws of Leadership',
    titleEs: 'Las 21 leyes irrefutables del liderazgo',
    author: 'John C. Maxwell',
    blurbEn: 'Timeless leadership principles for character and influence.',
    blurbEs: 'Principios atemporales de liderazgo: carácter e influencia.',
    themes: ['western_christian'],
    asin: '0785288376',
    coverUrl: '/freedom/book-covers/maxwell-21-laws.jpg',
    accent: '#DAA520',
    mark: '👑',
  },
  {
    id: 'maxwell-developing-leader',
    title: 'Developing the Leader Within You 2.0',
    titleEs: 'Desarrolle el líder que está en usted 2.0',
    author: 'John C. Maxwell',
    blurbEn: 'Personal growth as the root of leadership.',
    blurbEs: 'El crecimiento personal como raíz del liderazgo.',
    themes: ['western_christian'],
    asin: '0718073993',
    coverUrl: '/freedom/book-covers/maxwell-developing-leader.jpg',
    accent: '#B8860B',
    mark: '📈',
  },
  {
    id: 'newman-indoctrination',
    title: 'Indoctrinating Our Children to Death',
    titleEs: 'Indoctrinando a nuestros hijos hasta la muerte',
    author: 'Alex Newman',
    blurbEn: 'Education capture and the fight for parental rights.',
    blurbEs: 'Captura de la educación y la pelea por los derechos parentales.',
    themes: ['western_christian'],
    asin: '1944229990',
    coverUrl: '/freedom/book-covers/newman-indoctrination.svg',
    accent: '#556B2F',
    mark: '🏫',
  },
  {
    id: 'newman-crimes-educators',
    title: 'Crimes of the Educators',
    titleEs: 'Crímenes de los educadores',
    author: 'Alex Newman & Samuel Blumenfeld',
    blurbEn: 'How progressive schooling undermined literacy and liberty.',
    blurbEs: 'Cómo la escolarización progresista minó la alfabetización y la libertad.',
    themes: ['western_christian'],
    asin: '1938067134',
    coverUrl: '/freedom/book-covers/newman-crimes-educators.jpg',
    accent: '#6B8E23',
    mark: '📝',
  },
  {
    id: 'ramsey-total-money',
    title: 'The Total Money Makeover',
    titleEs: 'La transformación total de su dinero',
    author: 'Dave Ramsey',
    blurbEn: 'Debt-free living and biblical money stewardship.',
    blurbEs: 'Vida sin deudas y mayordomía bíblica del dinero.',
    themes: ['western_christian'],
    asin: '1595555277',
    coverUrl: '/freedom/book-covers/ramsey-total-money.jpg',
    accent: '#228B22',
    mark: '💵',
  },
  {
    id: 'kiyosaki-rich-dad',
    title: 'Rich Dad Poor Dad',
    titleEs: 'Padre rico, padre pobre',
    author: 'Robert T. Kiyosaki',
    blurbEn: 'Assets vs liabilities — financial freedom basics.',
    blurbEs: 'Activos vs pasivos: bases de la libertad financiera.',
    themes: ['western_christian'],
    asin: '1612680194',
    coverUrl: '/freedom/book-covers/kiyosaki-rich-dad.jpg',
    accent: '#32CD32',
    mark: '🏠',
  },
  {
    id: 'kiyosaki-cashflow',
    title: 'Cashflow Quadrant',
    titleEs: 'El cuadrante del flujo de dinero',
    author: 'Robert T. Kiyosaki',
    blurbEn: 'From employee to investor mindset.',
    blurbEs: 'Del empleado al inversor: cambio de mentalidad.',
    themes: ['western_christian'],
    asin: '1612680054',
    coverUrl: '/freedom/book-covers/kiyosaki-cashflow.jpg',
    accent: '#3CB371',
    mark: '📊',
  },
  {
    id: 'trump-art-of-deal',
    title: 'Trump: The Art of the Deal',
    titleEs: 'Trump: el arte de la negociación',
    author: 'Donald J. Trump',
    blurbEn: 'Negotiation, risk, and building under pressure.',
    blurbEs: 'Negociación, riesgo y construcción bajo presión.',
    themes: ['western_christian'],
    asin: '0399594493',
    coverUrl: '/freedom/book-covers/trump-art-of-deal.jpg',
    accent: '#FFD700',
    mark: '🏗',
  },
  {
    id: 'trump-save-america',
    title: 'Save America',
    titleEs: 'Salvar América',
    author: 'Donald J. Trump',
    blurbEn: 'America First agenda in the president’s own words.',
    blurbEs: 'Agenda America First en palabras del presidente.',
    themes: ['western_christian'],
    asin: 'B0D9HS4CWN',
    coverUrl: '/freedom/book-covers/trump-save-america.jpg',
    accent: '#FF4500',
    mark: '🇺🇸',
  },
  {
    id: 'lacalle-libertad-o-igualdad',
    title: 'Freedom or Equality',
    titleEs: 'Libertad o igualdad',
    author: 'Daniel Lacalle',
    blurbEn: 'Why freedom produces prosperity better than egalitarianism.',
    blurbEs: 'Por qué la libertad produce más prosperidad que el igualitarismo.',
    themes: ['western_christian'],
    asin: '1642934335',
    coverUrl: '/freedom/book-covers/lacalle-libertad-o-igualdad.jpg',
    accent: '#C0C0C0',
    mark: '🇪🇸',
  },
  {
    id: 'lacalle-escape-trampa',
    title: 'Escape from the Central Bank Trap',
    titleEs: 'La trampa de los bancos centrales',
    author: 'Daniel Lacalle',
    blurbEn: 'Monetary distortion and how free markets correct it.',
    blurbEs: 'Distorsión monetaria y cómo los mercados libres la corrigen.',
    themes: ['western_christian'],
    asin: '8423423433',
    coverUrl: '/freedom/book-covers/lacalle-escape-trampa.jpg',
    accent: '#A9A9A9',
    mark: '🏦',
  },
  {
    id: 'malone-lies-my-gov',
    title: 'Lies My Gov’t Told Me',
    titleEs: 'Mentiras que me contó mi gobierno',
    author: 'Robert W. Malone',
    blurbEn: 'mRNA, public health power, and scientific integrity.',
    blurbEs: 'ARNm, poder de la salud pública e integridad científica.',
    themes: ['bioconservatism'],
    asin: '151077324X',
    coverUrl: '/freedom/book-covers/malone-lies-my-gov.jpg',
    accent: '#4B0082',
    mark: '🧪',
  },
  {
    id: 'wheeler-tangle-truth',
    title: 'Tangle of Truth',
    titleEs: 'Enredo de verdad',
    author: 'Liz Wheeler',
    blurbEn: 'Clear thinking against media spin and cultural lies.',
    blurbEs: 'Pensamiento claro frente al spin mediático y las mentiras culturales.',
    themes: ['western_christian'],
    asin: '1637582393',
    coverUrl: '/freedom/book-covers/wheeler-tangle-truth.jpg',
    accent: '#FF69B4',
    mark: '🎤',
  },
  {
    id: 'berenson-unreported-truths',
    title: 'Unreported Truths about COVID-19',
    titleEs: 'Verdades no reportadas sobre el COVID-19',
    author: 'Alex Berenson',
    blurbEn: 'Independent reporting against pandemic orthodoxy.',
    blurbEs: 'Periodismo independiente frente a la ortodoxia pandémica.',
    themes: ['bioconservatism'],
    asin: '1953039014',
    coverUrl: '/freedom/book-covers/berenson-unreported-truths.jpg',
    accent: '#8A2BE2',
    mark: '📰',
  },
  {
    id: 'berenson-pandemia',
    title: 'Pandemia',
    titleEs: 'Pandemia',
    author: 'Alex Berenson',
    blurbEn: 'How fear and policy reshaped freedom.',
    blurbEs: 'Cómo el miedo y la política reconfiguraron la libertad.',
    themes: ['bioconservatism'],
    asin: '1684512489',
    coverUrl: '/freedom/book-covers/berenson-pandemia.jpg',
    accent: '#9932CC',
    mark: '🦠',
  },
  {
    id: 'adams-retaking-america',
    title: 'Retaking America',
    titleEs: 'Recuperar América',
    author: 'Nick Adams',
    blurbEn: 'Patriotism, masculinity, and defending the West.',
    blurbEs: 'Patriotismo, masculinidad y defensa de Occidente.',
    themes: ['western_christian'],
    asin: '1618688502',
    coverUrl: '/freedom/book-covers/adams-retaking-america.jpg',
    accent: '#B22222',
    mark: '🦅',
  },
  {
    id: 'adams-alpha',
    title: 'The American Boomerang',
    titleEs: 'El bumerán americano',
    author: 'Nick Adams',
    blurbEn: 'Why American exceptionalism still matters.',
    blurbEs: 'Por qué el excepcionalismo americano aún importa.',
    themes: ['western_christian'],
    asin: '1642932302',
    coverUrl: '/freedom/book-covers/adams-alpha.jpg',
    accent: '#DC143C',
    mark: '⭐',
  },
  {
    id: 'oreilly-killing-jesus',
    title: 'Killing Jesus',
    titleEs: 'Matar a Jesús',
    author: "Bill O'Reilly",
    blurbEn: 'Historical narrative of the Passion and Roman power.',
    blurbEs: 'Narrativa histórica de la Pasión y el poder romano.',
    themes: ['western_christian'],
    asin: '0805098542',
    coverUrl: '/freedom/book-covers/oreilly-killing-jesus.jpg',
    accent: '#8B0000',
    mark: '✝',
  },
  {
    id: 'oreilly-killing-lincoln',
    title: 'Killing Lincoln',
    titleEs: 'Matar a Lincoln',
    author: "Bill O'Reilly",
    blurbEn: 'Assassination that tested the American republic.',
    blurbEs: 'El asesinato que puso a prueba la república americana.',
    themes: ['western_christian'],
    asin: '0805093079',
    coverUrl: '/freedom/book-covers/oreilly-killing-lincoln.jpg',
    accent: '#A52A2A',
    mark: '🎩',
  },
  {
    id: 'posobiec-bulletproof',
    title: 'Bulletproof',
    titleEs: 'A prueba de balas',
    author: 'Jack Posobiec',
    blurbEn: 'Media warfare and surviving the culture war.',
    blurbEs: 'Guerra mediática y cómo sobrevivir la batalla cultural.',
    themes: ['western_christian'],
    asin: '1510783369',
    coverUrl: '/freedom/book-covers/posobiec-bulletproof.jpg',
    accent: '#2F2F2F',
    mark: '📡',
  },
  {
    id: 'posobiec-human-events',
    title: 'The Human Events Guide',
    titleEs: 'Guía Human Events',
    author: 'Jack Posobiec',
    blurbEn: 'News, narrative, and countering left media.',
    blurbEs: 'Noticias, narrativa y contrarrestar a los medios de izquierda.',
    themes: ['western_christian'],
    asin: '1637584280',
    coverUrl: '/freedom/book-covers/posobiec-human-events.jpg',
    accent: '#4A4A4A',
    mark: '🗞',
  },
  {
    id: 'walsh-church-of-cowards',
    title: 'Church of Cowards',
    titleEs: 'Iglesia de cobardes',
    author: 'Matt Walsh',
    blurbEn: 'A wake-up call to a soft, compromised Christianity.',
    blurbEs: 'Un llamado de atención a un cristianismo blando y comprometido.',
    themes: ['western_christian'],
    asin: '1684510923',
    coverUrl: '/freedom/book-covers/walsh-church-of-cowards.jpg',
    accent: '#000000',
    mark: '⛪',
  },
  {
    id: 'walsh-johnny-boys',
    title: 'Johnny the Walrus',
    titleEs: 'Johnny la morsa',
    author: 'Matt Walsh',
    blurbEn: 'Children’s parable against gender ideology.',
    blurbEs: 'Parábola infantil contra la ideología de género.',
    themes: ['bioconservatism'],
    asin: '1956007059',
    coverUrl: '/freedom/book-covers/walsh-johnny-boys.jpg',
    accent: '#1C1C1C',
    mark: '🦭',
  },
  {
    id: 'mccullough-courage-cure',
    title: 'The Courage to Face COVID-19',
    titleEs: 'El valor de enfrentar el COVID-19',
    author: 'Peter A. McCullough & John Leake',
    blurbEn: 'Early treatment protocols and medical free speech.',
    blurbEs: 'Protocolos de tratamiento temprano y libertad de expresión médica.',
    themes: ['bioconservatism'],
    asin: '1510776791',
    coverUrl: '/freedom/book-covers/mccullough-courage-cure.svg',
    accent: '#5F4B8B',
    mark: '🩺',
  },
  {
    id: 'martin-jimenez-club-bilderberg',
    title: 'The Bilderberg Club',
    titleEs: 'El Club Bilderberg',
    author: 'Cristina Martín Jiménez',
    blurbEn: 'Global elites, secrecy, and power networks.',
    blurbEs: 'Élites globales, secretismo y redes de poder.',
    themes: ['western_christian'],
    asin: '8413841141',
    coverUrl: '/freedom/book-covers/martin-jimenez-club-bilderberg.jpg',
    accent: '#800020',
    mark: '🕵',
  },
  {
    id: 'martin-jimenez-perestroika',
    title: 'Perestroika',
    titleEs: 'Perestroika',
    author: 'Cristina Martín Jiménez',
    blurbEn: 'Geopolitics and the unfinished fall of communism.',
    blurbEs: 'Geopolítica y la caída incompleta del comunismo.',
    themes: ['western_christian'],
    asin: '8413842342',
    coverUrl: '/freedom/book-covers/martin-jimenez-perestroika.jpg',
    accent: '#9B2335',
    mark: '🌍',
  },
  {
    id: 'melania-memoir',
    title: 'Melania',
    titleEs: 'Melania',
    author: 'Melania Trump',
    blurbEn: 'Memoir of the First Lady — resilience and private life in public.',
    blurbEs: 'Memorias de la Primera Dama: resiliencia y vida privada en lo público.',
    themes: ['western_christian'],
    asin: '1510782699',
    coverUrl: '/freedom/book-covers/melania-memoir.jpg',
    accent: '#E8B4B8',
    mark: '👗',
  },
  {
    id: 'stone-making-of-president',
    title: 'The Making of the President 2016',
    titleEs: 'La fabricación del presidente 2016',
    author: 'Roger Stone',
    blurbEn: 'Campaign warfare from a political operative’s view.',
    blurbEs: 'Guerra de campaña desde la mirada de un operativo político.',
    themes: ['western_christian'],
    asin: '1510722167',
    coverUrl: '/freedom/book-covers/stone-making-of-president.jpg',
    accent: '#708090',
    mark: '🎯',
  },
  {
    id: 'stone-stone-cold-truth',
    title: 'Stone’s Rules',
    titleEs: 'Las reglas de Stone',
    author: 'Roger Stone',
    blurbEn: 'Hard lessons of power, media, and politics.',
    blurbEs: 'Lecciones duras de poder, medios y política.',
    themes: ['western_christian'],
    asin: '1510740094',
    coverUrl: '/freedom/book-covers/stone-stone-cold-truth.jpg',
    accent: '#778899',
    mark: '♟',
  },
  {
    id: 'milei-el-camino',
    title: 'The Path of the Libertarian',
    titleEs: 'El camino del libertario',
    author: 'Javier Milei',
    blurbEn: 'Austrian economics against collectivism in Argentina.',
    blurbEs: 'Economía austriaca contra el colectivismo en Argentina.',
    themes: ['western_christian'],
    asin: '8423437221',
    coverUrl: '/freedom/book-covers/milei-el-camino.jpg',
    accent: '#6B2D5B',
    mark: '🦁',
  },
  {
    id: 'milei-capitalismo',
    title: 'Capitalism, Socialism and Everything In Between',
    titleEs: 'Capitalismo, socialismo y todo lo demás',
    author: 'Javier Milei',
    blurbEn: 'Why free markets beat state planning.',
    blurbEs: 'Por qué los mercados libres vencen a la planificación estatal.',
    themes: ['western_christian'],
    asin: '9504986099',
    coverUrl: '/freedom/book-covers/milei-capitalismo.jpg',
    accent: '#8B3A6B',
    mark: '🇦🇷',
  },
  {
    id: 'carlson-ship-fools',
    title: 'Ship of Fools',
    titleEs: 'Barco de tontos',
    author: 'Tucker Carlson',
    blurbEn: 'How a self-dealing elite lost America.',
    blurbEs: 'Cómo una élite autointeresada perdió a América.',
    themes: ['western_christian'],
    asin: '1501183664',
    coverUrl: '/freedom/book-covers/carlson-ship-fools.jpg',
    accent: '#1A1A2E',
    mark: '📺',
  },
  {
    id: 'carlson-long-slide',
    title: 'The Long Slide',
    titleEs: 'El largo desliz',
    author: 'Tucker Carlson',
    blurbEn: 'Essays on media decay and national decline.',
    blurbEs: 'Ensayos sobre la decadencia mediática y el declive nacional.',
    themes: ['western_christian'],
    asin: '1501183699',
    coverUrl: '/freedom/book-covers/carlson-long-slide.jpg',
    accent: '#16213E',
    mark: '✏',
  },
  {
    id: 'ramaswamy-woke-inc',
    title: 'Woke, Inc.',
    titleEs: 'Woke, Inc.',
    author: 'Vivek Ramaswamy',
    blurbEn: 'How corporate America sold out capitalism for identity politics.',
    blurbEs: 'Cómo el corporativismo vendió el capitalismo por la política de identidad.',
    themes: ['both'],
    asin: '1546090789',
    coverUrl: '/freedom/book-covers/ramaswamy-woke-inc.jpg',
    accent: '#FF8C00',
    mark: '🏢',
  },
  {
    id: 'ramaswamy-nation-victims',
    title: 'Nation of Victims',
    titleEs: 'Nación de víctimas',
    author: 'Vivek Ramaswamy',
    blurbEn: 'Identity, agency, and reclaiming American excellence.',
    blurbEs: 'Identidad, agencia y recuperar la excelencia americana.',
    themes: ['western_christian'],
    asin: '1546002964',
    coverUrl: '/freedom/book-covers/ramaswamy-nation-victims.jpg',
    accent: '#FF7F50',
    mark: '🏆',
  },
  {
    id: 'nosta-digital-health',
    title: 'The Digital Health Revolution',
    titleEs: 'La revolución de la salud digital',
    author: 'John Nosta',
    blurbEn: 'Tech, medicine, and human-centered innovation.',
    blurbEs: 'Tecnología, medicina e innovación centrada en la persona.',
    themes: ['bioconservatism'],
    asin: '1119900128',
    coverUrl: '/freedom/book-covers/nosta-digital-health.jpg',
    accent: '#20B2AA',
    mark: '💻',
  },
  {
    id: 'patel-hustle',
    title: 'Hustle',
    titleEs: 'Hustle',
    author: 'Neil Patel & Patrick Vlaskovits',
    blurbEn: 'Entrepreneurship, marketing, and building without permission.',
    blurbEs: 'Emprendimiento, marketing y construir sin permiso.',
    themes: ['western_christian'],
    asin: '1623367164',
    coverUrl: '/freedom/book-covers/patel-hustle.jpg',
    accent: '#00BFFF',
    mark: '📣',
  },
  {
    id: 'patel-digital-marketing',
    title: 'Hacking Growth',
    titleEs: 'Hacking Growth',
    author: 'Sean Ellis & Morgan Brown',
    blurbEn: 'Growth frameworks for products, marketing, and teams that scale.',
    blurbEs: 'Frameworks de crecimiento para productos, marketing y equipos que escalan.',
    themes: ['western_christian'],
    asin: '045149721X',
    coverUrl: '/freedom/book-covers/patel-digital-marketing.jpg',
    accent: '#1E90FF',
    mark: '📈',
  }
];

/**
 * Verified Amazon buy link (Associates tag).
 * - ISBN-10 / ASIN → product page /dp/{asin}
 * - Kindle-only / author codes still use /dp/ when present
 * - Fallback: keyword search with author + title
 */
export function bookAmazonUrl(book: RecommendedBook): string {
  const asin = book.asin?.trim();
  // Kindle / product ASINs (B0…, B07…, etc.) and ISBN-10
  if (asin && /^B0[0-9A-Z]{8,}$/i.test(asin)) {
    return amazonProductUrl(asin, 'com');
  }
  if (asin && /^[0-9A-Z]{10}$/i.test(asin)) {
    return amazonProductUrl(asin, 'com');
  }
  if (asin && asin.length >= 10 && !asin.includes(' ')) {
    return amazonProductUrl(asin, 'com');
  }
  return amazonSearchUrl(
    `${book.author} ${book.title || book.titleEs}`.trim(),
    'com'
  );
}

/**
 * Candidate cover image URLs (try in order).
 * Prefer Open Library + explicit coverUrl; Amazon P/ paths last (often 1×1 placeholders in-browser).
 */
export function bookCoverCandidates(book: RecommendedBook): string[] {
  const urls: string[] = [];
  // Same-origin hosted cover first (deployed with the app — always loads)
  if (book.coverUrl?.startsWith('/')) urls.push(book.coverUrl);
  urls.push(`/freedom/book-covers/${book.id}.jpg`);
  if (book.coverUrl && !book.coverUrl.startsWith('/')) urls.push(book.coverUrl);
  if (book.asin) {
    const a = book.asin.trim();
    if (/^[0-9]{9}[0-9Xx]$/.test(a)) {
      urls.push(`https://covers.openlibrary.org/b/isbn/${a}-L.jpg`);
    }
    if (/^B0[0-9A-Z]{8,}$/i.test(a) || /^[0-9A-Z]{10}$/i.test(a)) {
      urls.push(
        `https://m.media-amazon.com/images/P/${a}.01._SCLZZZZZZZ_SX400_.jpg`
      );
    }
  }
  return [...new Set(urls.filter(Boolean))];
}

/** Search queries for Open Library / Google Books cover lookup (best first). */
export function bookCoverSearchQueries(book: RecommendedBook): string[] {
  const authorLast = book.author.split(/\s+/).filter(Boolean).slice(-1)[0] || book.author;
  const qs = [
    `${book.titleEs} ${book.author}`,
    `${book.title} ${book.author}`,
    `${book.titleEs} ${authorLast}`,
    `${book.title} ${authorLast}`,
    book.titleEs,
    book.title,
  ]
    .map((q) => q.trim())
    .filter(Boolean);
  return [...new Set(qs)];
}

/** @deprecated use bookCoverSearchQueries */
export function bookCoverSearchQuery(book: RecommendedBook): string {
  return bookCoverSearchQueries(book)[0] || `${book.title} ${book.author}`.trim();
}

