/**
 * Central SEO / social metadata for the Salvazion app (salvazion.org).
 */
import { APP_URL, MARKETING_URL, SUPPORT_EMAIL } from '@/lib/config/site';

export const SEO = {
  siteName: 'Salvazion',
  legalName: 'Salvazion, Inc.',
  tagline: 'Make Salvation, Health and Freedom Great Again',
  /** Primary HTML title (root + OG) */
  title: 'Salvazion | Make Salvation, Health and Freedom Great Again',
  titleTemplate: '%s | Salvazion',
  /**
   * Meta description — bilingual keywords, under ~160–170 chars ideal;
   * slightly longer is OK for rich social previews.
   */
  description:
    'Salvazion: the platform that restores the human person. Make Salvation, Health and Freedom Great Again. One freemium App — offline Bible, devotionals, health & wearables, Freedom library, Phalanx community, Salvazion AI and $SALVAZION on Solana.',
  descriptionEs:
    'Salvazion: la plataforma que restaura a la persona humana. Make Salvation, Health and Freedom Great Again. Una sola App freemium — Biblia offline, devocional, salud y wearables, biblioteca Freedom, comunidad Phalanx, IA Salvazion y $SALVAZION en Solana.',
  descriptionPt:
    'Salvazion: a plataforma que restaura a pessoa humana. Make Salvation, Health and Freedom Great Again. Um só App freemium — Bíblia offline, devocional, saúde e wearables, biblioteca Freedom, comunidade Phalanx, IA Salvazion e $SALVAZION na Solana.',
  keywords: [
    'Salvazion',
    'Salvation Health Freedom',
    'Make Salvation Health and Freedom Great Again',
    'Salvazion blog',
    'Salvazion articles',
    'Salvazion X articles',
    '@salvazion_',
    'Christian app',
    'Bible offline',
    'devotional',
    'BioConservatism',
    'Western Christian Culture',
    'faith health freedom',
    'Salvation articles',
    'Health articles',
    'Freedom articles',
    'Solana',
    'SALVAZION token',
    'Green Lion coach',
    'Phalanx community',
    'wearables health',
    'app cristiana',
    'Biblia offline',
    'devocional',
    'BioConservadurismo',
    'cultura cristiana occidental',
    'artículos Salvazion',
    'blog Salvazion',
    'app cristã',
    'Bíblia offline',
    'devocional',
    'BioConservadorismo',
    'cultura cristã ocidental',
    'artigos Salvazion',
    'Almeida Revista e Corrigida',
    'ARC',
  ],
  locale: 'en_US',
  alternateLocale: 'es_ES',
  alternateLocalePt: 'pt_BR',
  /** Absolute URLs for crawlers / social */
  url: APP_URL,
  marketingUrl: MARKETING_URL,
  supportEmail: SUPPORT_EMAIL,
  /**
   * OG/Twitter images are generated by app/opengraph-image.tsx
   * and app/twitter-image.tsx (Next.js file convention).
   * Fallback absolute asset for JSON-LD / non-OG consumers:
   */
  imageFallback: '/salvazion-logo-green-lion.png',
  ogImageAlt:
    'Salvazion Green Lion — Make Salvation, Health and Freedom Great Again',
  twitterHandle: '@salvazion',
  category: 'Lifestyle',
  founders: [
    {
      name: 'Cristian Cortés',
      jobTitle: 'CEO & Founder',
      sameAs: [] as string[],
    },
    {
      name: 'Beatriz Isler',
      jobTitle: 'COO & Founder',
      sameAs: ['https://www.linkedin.com/in/beatriz-isler/'] as string[],
    },
  ],
  pricing: {
    free: 0,
    premiumMonthly: 49,
    premiumAnnual: 468,
    currency: 'USD',
  },
} as const;

export function absoluteUrl(path = '/'): string {
  const base = SEO.url.replace(/\/$/, '');
  if (!path || path === '/') return `${base}/`;
  return `${base}${path.startsWith('/') ? path : `/${path}`}`;
}
