/**
 * Central SEO / social metadata for the Salvazion app (salvazion.org).
 */
import { APP_URL, MARKETING_URL, SUPPORT_EMAIL } from '@/lib/config/site';

export const SEO = {
  siteName: 'Salvazion',
  legalName: 'Salvazion, Inc.',
  tagline: 'Make Salvation, Health and Freedom Great Again',
  /** Primary HTML title (root + OG) */
  title: 'Salvazion | Make Salvation, Health and Freedom Great Again',
  titleTemplate: '%s | Salvazion',
  /**
   * Meta description — bilingual keywords, under ~160–170 chars ideal;
   * slightly longer is OK for rich social previews.
   */
  description:
    'Salvazion: Make Salvation, Health and Freedom Great Again. Freemium app — offline Bible, devotionals, health & wearables, Freedom library, Phalanx community, Green Lion coach and $SALVAZION on Solana. Western Christian Culture & BioConservatism.',
  descriptionEs:
    'Salvazion: Hacer Salvación, Salud y Libertad geniales otra vez. App freemium — Biblia offline, devocional, salud y wearables, biblioteca Freedom, comunidad Phalanx, coach León Verde y $SALVAZION en Solana. Cultura Cristiana Occidental y BioConservadurismo.',
  descriptionPt:
    'Salvazion: Tornar Salvação, Saúde e Liberdade grandiosas de novo. App freemium — Bíblia offline, devocional, saúde e wearables, biblioteca Freedom, comunidade Phalanx, coach Leão Verde e $SALVAZION na Solana. Cultura Cristã Ocidental e BioConservadorismo.',
  keywords: [
    'Salvazion',
    'Salvation Health Freedom',
    'Make Salvation Health and Freedom Great Again',
    'Salvazion blog',
    'Salvazion articles',
    'Salvazion X articles',
    '@salvazion_',
    'Christian app',
    'Bible offline',
    'devotional',
    'BioConservatism',
    'Western Christian Culture',
    'faith health freedom',
    'Salvation articles',
    'Health articles',
    'Freedom articles',
    'Solana',
    'SALVAZION token',
    'Green Lion coach',
    'Phalanx community',
    'wearables health',
    'app cristiana',
    'Biblia offline',
    'devocional',
    'BioConservadurismo',
    'cultura cristiana occidental',
    'artículos Salvazion',
    'blog Salvazion',
    'app cristã',
    'Bíblia offline',
    'devocional',
    'BioConservadorismo',
    'cultura cristã ocidental',
    'artigos Salvazion',
    'Almeida Revista e Corrigida',
    'ARC',
  ],
  locale: 'en_US',
  alternateLocale: 'es_ES',
  alternateLocalePt: 'pt_BR',
  /** Absolute URLs for crawlers / social */
  url: APP_URL,
  marketingUrl: MARKETING_URL,
  supportEmail: SUPPORT_EMAIL,
  /**
   * OG/Twitter images are generated by app/opengraph-image.tsx
   * and app/twitter-image.tsx (Next.js file convention).
   * Fallback absolute asset for JSON-LD / non-OG consumers:
   */
  imageFallback: '/salvazion-logo-green-lion.png',
  ogImageAlt:
    'Salvazion Green Lion — Make Salvation, Health and Freedom Great Again',
  twitterHandle: '@salvazion',
  category: 'Lifestyle',
  founders: [
    {
      name: 'Cristian Cortés',
      jobTitle: 'CEO & Founder',
      sameAs: [] as string[],
    },
    {
      name: 'Beatriz Isler',
      jobTitle: 'COO & Founder',
      sameAs: ['https://www.linkedin.com/in/beatriz-isler/'] as string[],
    },
  ],
  pricing: {
    free: 0,
    premiumMonthly: 49,
    premiumAnnual: 468,
    currency: 'USD',
  },
} as const;

export function absoluteUrl(path = '/'): string {
  const base = SEO.url.replace(/\/$/, '');
  if (!path || path === '/') return `${base}/`;
  return `${base}${path.startsWith('/') ? path : `/${path}`}`;
}
