import type { WearableCatalogItem } from './types';

/** Supported brands / device classes users can link */
export const WEARABLE_CATALOG: WearableCatalogItem[] = [
  {
    brandId: 'generic_ble_hr',
    name: 'Bluetooth heart-rate monitor',
    nameEs: 'Monitor cardíaco Bluetooth',
    namePt: 'Monitor cardíaco Bluetooth',
    category: 'chest_strap',
    connectModes: ['web_bluetooth_hr'],
    metrics: ['heart_rate', 'active_minutes'],
    icon: '❤️',
    note: 'Works now via Web Bluetooth (chest straps, some watches/bands).',
    noteEs: 'Funciona ahora con Web Bluetooth (cintas, algunos relojes/bandas).',
    notePt: 'Funciona agora com Web Bluetooth (cintas, alguns relógios/pulseiras).',
  },
  {
    brandId: 'polar',
    name: 'Polar (H10 / watches)',
    nameEs: 'Polar (H10 / relojes)',
    namePt: 'Polar (H10 / relógios)',
    category: 'chest_strap',
    connectModes: ['web_bluetooth_hr', 'manual'],
    metrics: ['heart_rate', 'steps', 'active_minutes', 'calories'],
    icon: '📡',
  },
  {
    brandId: 'apple_watch',
    name: 'Apple Watch',
    nameEs: 'Apple Watch',
    namePt: 'Apple Watch',
    category: 'watch',
    connectModes: ['healthkit', 'manual'],
    metrics: ['heart_rate', 'resting_hr', 'hrv', 'steps', 'active_minutes', 'sleep_hours', 'calories'],
    icon: '⌚',
    note: 'HealthKit in Salvazion native shell (iOS). Manual fallback on web.',
    noteEs: 'HealthKit en el shell nativo Salvazion (iOS). Manual en web.',
    notePt: 'HealthKit no shell nativo Salvazion (iOS). Manual na web.',
  },
  {
    brandId: 'garmin',
    name: 'Garmin',
    nameEs: 'Garmin',
    namePt: 'Garmin',
    category: 'watch',
    connectModes: ['oauth', 'manual'],
    metrics: ['heart_rate', 'steps', 'active_minutes', 'sleep_hours', 'distance_km', 'calories', 'stress'],
    icon: '⌚',
    note: 'OAuth 2.0 via Garmin Connect Developer Program.',
    noteEs: 'OAuth 2.0 con Garmin Connect Developer Program.',
    notePt: 'OAuth 2.0 com Garmin Connect Developer Program.',
  },
  {
    brandId: 'fitbit',
    name: 'Fitbit (Google Health)',
    nameEs: 'Fitbit (Google Health)',
    namePt: 'Fitbit (Google Health)',
    category: 'band',
    connectModes: ['oauth', 'manual'],
    metrics: ['heart_rate', 'steps', 'active_minutes', 'sleep_hours', 'calories', 'spo2'],
    icon: '⌚',
    note: 'Uses Google Health API (legacy Fitbit Web API ends Sep 2026). Needs GOOGLE_HEALTH_CLIENT_ID/SECRET.',
    noteEs:
      'Usa Google Health API (la Fitbit Web API legacy termina en sep 2026). Requiere GOOGLE_HEALTH_CLIENT_ID/SECRET.',
    notePt:
      'Usa a Google Health API (a Fitbit Web API legacy termina em set 2026). Requer GOOGLE_HEALTH_CLIENT_ID/SECRET.',
  },
  {
    brandId: 'samsung',
    name: 'Samsung Galaxy Watch / Ring',
    nameEs: 'Samsung Galaxy Watch / Ring',
    namePt: 'Samsung Galaxy Watch / Ring',
    category: 'watch',
    connectModes: ['health_connect', 'manual'],
    metrics: ['heart_rate', 'steps', 'sleep_hours', 'spo2', 'stress'],
    icon: '⌚',
    note: 'Health Connect in Salvazion native shell (Android).',
    noteEs: 'Health Connect en el shell nativo Salvazion (Android).',
    notePt: 'Health Connect no shell nativo Salvazion (Android).',
  },
  {
    brandId: 'oura',
    name: 'Oura Ring',
    nameEs: 'Anillo Oura',
    namePt: 'Anel Oura',
    category: 'ring',
    connectModes: ['oauth', 'manual'],
    metrics: ['resting_hr', 'hrv', 'sleep_hours', 'readiness', 'steps', 'calories'],
    icon: '💍',
    note: 'OAuth 2.0 via Oura Cloud API.',
    noteEs: 'OAuth 2.0 con Oura Cloud API.',
    notePt: 'OAuth 2.0 com Oura Cloud API.',
  },
  {
    brandId: 'whoop',
    name: 'WHOOP',
    nameEs: 'WHOOP',
    namePt: 'WHOOP',
    category: 'band',
    connectModes: ['oauth', 'manual'],
    metrics: ['resting_hr', 'hrv', 'sleep_hours', 'readiness', 'calories'],
    icon: '💪',
    note: 'OAuth 2.0 via WHOOP Developer API.',
    noteEs: 'OAuth 2.0 con WHOOP Developer API.',
    notePt: 'OAuth 2.0 com WHOOP Developer API.',
  },
  {
    brandId: 'ultrahuman',
    name: 'Ultrahuman Ring',
    nameEs: 'Anillo Ultrahuman',
    namePt: 'Anel Ultrahuman',
    category: 'ring',
    connectModes: ['manual', 'health_connect', 'healthkit'],
    metrics: ['resting_hr', 'hrv', 'sleep_hours', 'readiness', 'spo2'],
    icon: '💍',
  },
  {
    brandId: 'amazfit',
    name: 'Amazfit / Zepp',
    nameEs: 'Amazfit / Zepp',
    namePt: 'Amazfit / Zepp',
    category: 'watch',
    connectModes: ['manual', 'web_bluetooth_hr'],
    metrics: ['heart_rate', 'steps', 'sleep_hours', 'active_minutes'],
    icon: '⌚',
  },
  {
    brandId: 'withings',
    name: 'Withings (scale / watch)',
    nameEs: 'Withings (báscula / reloj)',
    namePt: 'Withings (balança / relógio)',
    category: 'scale',
    connectModes: ['manual'],
    metrics: ['weight_kg', 'body_fat', 'heart_rate', 'sleep_hours'],
    icon: '⚖️',
    note: 'Log weight and vitals manually from the Withings app.',
    noteEs: 'Registra peso y vitals manualmente desde la app Withings.',
    notePt: 'Registre peso e vitais manualmente no app Withings.',
  },
  {
    brandId: 'xiaomi',
    name: 'Xiaomi / Mi Band',
    nameEs: 'Xiaomi / Mi Band',
    namePt: 'Xiaomi / Mi Band',
    category: 'band',
    connectModes: ['manual', 'web_bluetooth_hr'],
    metrics: ['heart_rate', 'steps', 'sleep_hours', 'active_minutes'],
    icon: '⌚',
  },
  {
    brandId: 'generic_other',
    name: 'Other wearable / monitor',
    nameEs: 'Otro wearable / monitor',
    namePt: 'Outro wearable / monitor',
    category: 'other',
    connectModes: ['manual'],
    metrics: ['heart_rate', 'steps', 'sleep_hours', 'active_minutes', 'weight_kg'],
    icon: '📟',
  },
];

export function getCatalogItem(brandId: string) {
  return WEARABLE_CATALOG.find((c) => c.brandId === brandId);
}

export function catalogByCategory() {
  const map = new Map<string, WearableCatalogItem[]>();
  for (const item of WEARABLE_CATALOG) {
    const list = map.get(item.category) || [];
    list.push(item);
    map.set(item.category, list);
  }
  return map;
}
